version: '3'
services:
  neo4j:
    image: neo4j:3.1.3
    volumes:
      - graph-data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      # - NEO4J_AUTH=${NEO4J_LOGIN}/${NEO4J_PASSWORD}
      - NEO4J_AUTH=none
volumes:
  graph-data:
