version: '3'
services:
  neo4j:
    build: ./neo4j-apoc
    image: neo4j-apoc
    volumes:
      - graph-data:/var/lib/neo4j/data
      # - ./conf:/conf
      - ./import:/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      # - NEO4J_AUTH=${NEO4J_LOGIN}/${NEO4J_PASSWORD}
      - NEO4J_AUTH=none
volumes:
  graph-data:

